name: Sync

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  repo-arr:
    name: Create Repository Array
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: create-arr
        with:
          script: |
            const result = await github.graphql(`{ 
              organization(login:"${context.payload.organization.login}") {
                repositories(first:100) {
                  nodes {
                    name
                  }
                }
              }
            }`);
            console.log(JSON.stringify(result, null, 2));
            return result.organization.repositories.nodes
              .map(repo => repo.name)
              .filter(repo => repo !== context.payload.repository.name);
          github-token: ${{ secrets.GH_TOKEN }}
    outputs:
      repos: ${{ steps.create-arr.outputs.result }}

  sync:
    name: Sync Repository
    needs:
      - repo-arr
    strategy:
      matrix:
        repo: ${{ fromJson(needs.repo-arr.outputs.repos) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository ${{ matrix.repo }}
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.organization.login }}/${{ matrix.repo }}
          token: ${{ secrets.GH_TOKEN }}
      - run: |
          git config --global user.name 'actions-user'
          git config --global user.email 'actions-user@users.noreply.github.com'
      - run: git remote add source https://github.com/${{ github.event.organization.login }}/${{ github.event.repository.name }}
      - run: git fetch source
      - run: git merge --allow-unrelated-histories --squash -X theirs source/main
      - run: |
          for fileName in sync.yml README.md; do
            git reset HEAD -- $fileName
            git clean -f -q -- $fileName
          done 
      - run: git diff-index --quiet HEAD || git commit -am "Organization sync"
      - run: git push