name: Sync

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  repo-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: matrix
        with:
          script: |
            return ['123', '456', '789']
    outputs:
      matrix: ${{ steps.matrix.outputs.result }}
  
  repo-print:
    needs: repo-matrix
    strategy:
      matrix:
        repos: ${{ fromJson(needs.repo-matrix.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'test'
            
