name: Sync

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  repo-arr:
    name: Create Repository Array
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: create-arr
        with:
          script: |
            const result = await github.graphql(`{ 
              organization(login:"${context.payload.organization.login}") {
                repositories(first:100) {
                  nodes {
                    name
                  }
                }
              }
            }`);
            console.log(JSON.stringify(result, null, 2));
            return result.organization.repositories.nodes
              .map(repo => repo.name)
              .filter(repo => repo !== context.payload.repository.name);
    outputs:
      repos: ${{ steps.create-arr.outputs.result }}
  
  sync:
    name: Sync Repos
    needs: repo-arr
    strategy:
      matrix:
        repo: ${{ fromJson(needs.repo-arr.outputs.repos) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.event.repository.name }} repo
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}
      - name: Checkout ${{ matrix.repo }} repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.organization.login }}/${{ matrix.repo }}
          path: ${{ matrix.repo }}
          token: ${{ secrets.GH_TOKEN }}
      - run: ls -al
      # - run: |
      #     rsync -avrc --delete \
      #     --exclude=README.md \
      #     --exclude=.git* \
      #     ${{ github.event.repository.name }} ${{ matrix.repo }}
      - name: Create Patch2
        working-directory: ${{ github.event.repository.name }}
        run: echo $(pwd)
      - name: Create Patch
        working-directory: ${{ github.event.repository.name }}
        run: git format-patch HEAD^ --stdout > ../revision.patch
      - name: Apply Patch
        working-directory: ${{ matrix.repo }}
        run: git apply ../revision.patch
      - name: Commit
        working-directory: ${{ matrix.repo }}
        run: |
          git config --global user.name 'actions-user'
          git config --global user.email 'actions-user@users.noreply.github.com'
          git add -A
          git diff-index --quiet HEAD || git commit -am "Organization sync"
          git push
