name: Sync Repositories

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  get-org-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/get-org-repos@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}
        id: get-org-repos
    outputs:
      repos: ${{ steps.get-org-repos.outputs.repos }}

  patch:
    name: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git format-patch --root --stdout | tee source.patch
      - uses: actions/upload-artifact@v2
        with:
          name: patch
          path: source.patch

  sync:
    needs:
      - get-org-repos
      - patch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ fromJson(needs.get-org-repos.outputs.repos) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.organization.login }}/${{ matrix.repo }}
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/download-artifact@v2
        with:
          name: patch
      - run: git apply --check --verbose --summary source.patch
      - run: git apply --verbose source.patch
      - run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
      - run: git diff-index --quiet HEAD || git commit -am "Organization sync"
      - run: git push
